
server:
  port: 8761
spring:
  application:
    name: eurakaserver
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
    client:
      ip-address: 127.0.0.1
eureka:
  server:
    peer-node-read-timeout-ms: 30000
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: true  #为false意味着自身仅作为服务器，不作为客户端；
    fetch-registry: true  #为false意味着无需注册自身。
    healthcheck:
      enabled: true


